#!/bin/bash

DOWN=$(tail -n 1 /srv/http/log/speedtest.log | awk -F ',' '{print $1}')
UP=$(tail -n 1 /srv/http/log/speedtest.log | awk -F ',' '{print $2}')

good ()
        {

        echo "Speeds are good. D: $DOWN U: $UP Mb/s | https://mgh.solutions/logs/speedtest.log"

        }

bad ()
        {

        echo "Speeds are bad. D: $DOWN U: $UP Mb/s"

        }

warning ()
        {

        echo "Speeds are not s'good. D: $DOWN U: $UP Mb/s"

        }

main ()
        {

        if [[ $DOWN -ge 150 ]]; then
        echo 1
                if [[ $UP -ge 10 ]]; then
                        good;
                fi
        else
        echo 2
                if [[ $DOWN -ge 75 ]]; then
                echo 3
                        if [[ $UP -ge 5 ]]; then
                                warning;
                        else
                                bad;
                        fi
                else
                        bad;
                fi
        fi

        }

main;
