#!/bin/bash

DOWN=$(cat /srv/http/log/speedtest.last | awk -F ',' '{print $1}')
UP=$(cat /srv/http/log/speedtest.last | awk -F ', ' '{print $2}' | awk -F ',' '{print $1}')

#echo $DOWN
#echo $UP

good ()
        {

        echo "Speeds are good. D: $DOWN U: $UP Mb/s"
        return 0

        }

bad ()
        {

        echo "Speeds are bad. D: $DOWN U: $UP Mb/s"
        return 2

        }

warning ()
        {

        echo "Speeds are not s'good. D: $DOWN U: $UP Mb/s"
        return 1

        }

main ()
        {

        if [[ $DOWN -ge 500 ]]; then
                if [[ $UP -ge 400 ]]; then
                        good;
                else
                        if [[ $UP -ge 300 ]]; then
                                warning;
                        else
                                bad;
                        fi
                fi
        else
                if [[ $DOWN -ge 400 ]]; then
                        if [[ $UP -ge 300 ]]; then
                                warning;
                        else
                                bad;
                        fi
                else
                        bad;
                fi
        fi

        }

main;
