#!/bin/bash

DOWN=$(tail -n 1 /speedtest.log | awk -F ',' '{print $1}')
UP=$(tail -n 1 /speedtest.log | awk -F ',' '{print $2}')

good ()
        {

        echo "Speeds are good. D: $DOWN U: $UP Mb/s"

        }

bad ()
        {

        echo "Speeds are bad. D: $DOWN U: $UP Mb/s"

        }

warning ()
        {

        echo "Speeds are not s'good. D: $DOWN U: $UP Mb/s"

        }

main ()
        {

        if [[ $DOWN -ge 150 ]]; then
                if [[ $UP -ge 10 ]]; then
                        good;
                fi
        else
                if [[ $DOWN -ge 75 ]]; then
                        if [[ $UP -ge 5 ]]; then
                                warning;
                        else
                                bad;
                        fi
                fi
        fi

        }

main;
